apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-pagamento-deployment
  namespace: lanchonete-pagamento
  labels:
    app: ds-lanchonete-pagamento
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ds-lanchonete-pagamento
  template:
    metadata:
      labels:
        app: ds-lanchonete-pagamento
    spec:
      containers:
        - name: lanchonete-pagamento
          image: edureef42/lanchonete-pagamento:3.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prd"
            - name: mongo_host
              valueFrom:
                configMapKeyRef:
                  name: pagamento-configmap
                  key: mongo_host
            - name: mongo_user
              valueFrom:
                configMapKeyRef:
                  name: pagamento-configmap
                  key: mongo_user
            - name: mongo_password
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_password
            - name: mongo_db
              valueFrom:
                configMapKeyRef:
                  name: pagamento-configmap
                  key: mongo_db
            - name: LANCHONETE_PEDIDO_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: pagamento-configmap
                  key: LANCHONETE_PEDIDO_SERVICE_URL
          livenessProbe:
            httpGet:
              path: /lanchonete-pagamento/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /lanchonete-pagamento/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
