apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-pagamento-deployment
  namespace: lanchonete-pagamento
  labels:
    app: ds-lanchonete-pagamento
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ds-lanchonete-pagamento
  template:
    metadata:
      labels:
        app: ds-lanchonete-pagamento
    spec:
      containers:
        - name: lanchonete-pagamento
          image: edureef42/lanchonete-pagamento:1.9
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prd"
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: MONGO_HOST
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: MONGO_DB
            - name: LANCHONETE_PEDIDO_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: LANCHONETE_PEDIDO_SERVICE_URL
          livenessProbe:
            httpGet:
              path: /lanchonete-pagamento/actuator/health
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /lanchonete-pagamento/actuator/health
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 5
