apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
  namespace: lanchonete-pagamento
  labels:
    app: cm-mongo
data:
  MONGO_HOST: "mongodb-cluster.cluster-czu4isocm08k.us-east-1.docdb.amazonaws.com"
  MONGO_DB: "lanchonete_pagamento"
  MONGO_USER: "lanchonete_pagamento_user"
  LANCHONETE_PEDIDO_SERVICE_URL: "http://a1c592e5b9fcb424dbcf08123b82488a-2070148428.us-east-1.elb.amazonaws.com:8080/lanchonete-pedido"

