apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: lanchonete-pagamento
  labels:
    app: sc-mongo
type: Opaque
data:
  password: bGFuY2hvbmV0ZV9wYWdhbWVudG9fcGFzc3dvcmQ= # Base64 de 'lanchonete_pagamento_password'