spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/${MONGO_DB}?tls=true&tlsCAFile=/tmp/global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: ${MONGO_DB}

lanchonete:
  pedido:
    url: ${LANCHONETE_PEDIDO_SERVICE_URL}