spring:
  profiles:
    active: ${springProfile:local}
  application:
    name: lanchonete-api-pagamento
server:
  servlet:
    context-path: /lanchonete-pagamento
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
