apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  namespace: lanchonete-pagamento
  labels:
    type: local
    app: pv-mongo
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: lanchonete-pagamento
  labels:
    app: pvc-mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi